// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package stash

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// FindGalleriesFindGalleriesFindGalleriesResultType includes the requested fields of the GraphQL type FindGalleriesResultType.
type FindGalleriesFindGalleriesFindGalleriesResultType struct {
	Count     int                                                                 `json:"count"`
	Galleries []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery `json:"galleries"`
}

// GetCount returns FindGalleriesFindGalleriesFindGalleriesResultType.Count, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultType) GetCount() int { return v.Count }

// GetGalleries returns FindGalleriesFindGalleriesFindGalleriesResultType.Galleries, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultType) GetGalleries() []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery {
	return v.Galleries
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery includes the requested fields of the GraphQL type Gallery.
// The GraphQL type's documentation follows.
//
// Gallery type
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery struct {
	Id          string                                                                                 `json:"id"`
	Title       string                                                                                 `json:"title"`
	Date        string                                                                                 `json:"date"`
	Details     string                                                                                 `json:"details"`
	Rating100   int                                                                                    `json:"rating100"`
	Organized   bool                                                                                   `json:"organized"`
	Created_at  time.Time                                                                              `json:"created_at"`
	Updated_at  time.Time                                                                              `json:"updated_at"`
	Image_count int                                                                                    `json:"image_count"`
	Folder      FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder                `json:"folder"`
	Files       []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile    `json:"files"`
	Studio      FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio                `json:"studio"`
	Tags        []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag             `json:"tags"`
	Performers  []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer `json:"performers"`
}

// GetId returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Id, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetId() string {
	return v.Id
}

// GetTitle returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Title, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetTitle() string {
	return v.Title
}

// GetDate returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Date, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetDate() string {
	return v.Date
}

// GetDetails returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Details, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetDetails() string {
	return v.Details
}

// GetRating100 returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Rating100, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetRating100() int {
	return v.Rating100
}

// GetOrganized returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Organized, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetOrganized() bool {
	return v.Organized
}

// GetCreated_at returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Created_at, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetCreated_at() time.Time {
	return v.Created_at
}

// GetUpdated_at returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Updated_at, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetUpdated_at() time.Time {
	return v.Updated_at
}

// GetImage_count returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Image_count, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetImage_count() int {
	return v.Image_count
}

// GetFolder returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Folder, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetFolder() FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder {
	return v.Folder
}

// GetFiles returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Files, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetFiles() []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile {
	return v.Files
}

// GetStudio returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Studio, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetStudio() FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio {
	return v.Studio
}

// GetTags returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Tags, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetTags() []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag {
	return v.Tags
}

// GetPerformers returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Performers, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetPerformers() []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer {
	return v.Performers
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile includes the requested fields of the GraphQL type GalleryFile.
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile struct {
	Path string `json:"path"`
}

// GetPath returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile.Path, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile) GetPath() string {
	return v.Path
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder includes the requested fields of the GraphQL type Folder.
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder struct {
	Path string `json:"path"`
}

// GetPath returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder.Path, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder) GetPath() string {
	return v.Path
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer includes the requested fields of the GraphQL type Performer.
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer struct {
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	Birthdate string     `json:"birthdate"`
	Gender    GenderEnum `json:"gender"`
}

// GetId returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer.Id, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer) GetId() string {
	return v.Id
}

// GetName returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer.Name, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer) GetName() string {
	return v.Name
}

// GetBirthdate returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer.Birthdate, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer) GetBirthdate() string {
	return v.Birthdate
}

// GetGender returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer.Gender, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryPerformersPerformer) GetGender() GenderEnum {
	return v.Gender
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio includes the requested fields of the GraphQL type Studio.
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio.Id, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio) GetId() string {
	return v.Id
}

// GetName returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio.Name, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryStudio) GetName() string {
	return v.Name
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag includes the requested fields of the GraphQL type Tag.
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag.Id, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag) GetId() string {
	return v.Id
}

// GetName returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag.Name, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryTagsTag) GetName() string {
	return v.Name
}

// FindGalleriesResponse is returned by FindGalleries on success.
type FindGalleriesResponse struct {
	FindGalleries FindGalleriesFindGalleriesFindGalleriesResultType `json:"findGalleries"`
}

// GetFindGalleries returns FindGalleriesResponse.FindGalleries, and is useful for accessing the field via an interface.
func (v *FindGalleriesResponse) GetFindGalleries() FindGalleriesFindGalleriesFindGalleriesResultType {
	return v.FindGalleries
}

// FindScenesFindScenesFindScenesResultType includes the requested fields of the GraphQL type FindScenesResultType.
type FindScenesFindScenesFindScenesResultType struct {
	Count  int                                                   `json:"count"`
	Scenes []FindScenesFindScenesFindScenesResultTypeScenesScene `json:"scenes"`
}

// GetCount returns FindScenesFindScenesFindScenesResultType.Count, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultType) GetCount() int { return v.Count }

// GetScenes returns FindScenesFindScenesFindScenesResultType.Scenes, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultType) GetScenes() []FindScenesFindScenesFindScenesResultTypeScenesScene {
	return v.Scenes
}

// FindScenesFindScenesFindScenesResultTypeScenesScene includes the requested fields of the GraphQL type Scene.
type FindScenesFindScenesFindScenesResultTypeScenesScene struct {
	Id         string                                                                   `json:"id"`
	Title      string                                                                   `json:"title"`
	Date       string                                                                   `json:"date"`
	Details    string                                                                   `json:"details"`
	Rating100  int                                                                      `json:"rating100"`
	Organized  bool                                                                     `json:"organized"`
	Created_at time.Time                                                                `json:"created_at"`
	Updated_at time.Time                                                                `json:"updated_at"`
	Files      []FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile      `json:"files"`
	Studio     FindScenesFindScenesFindScenesResultTypeScenesSceneStudio                `json:"studio"`
	Tags       []FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag             `json:"tags"`
	Performers []FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer `json:"performers"`
}

// GetId returns FindScenesFindScenesFindScenesResultTypeScenesScene.Id, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetId() string { return v.Id }

// GetTitle returns FindScenesFindScenesFindScenesResultTypeScenesScene.Title, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetTitle() string { return v.Title }

// GetDate returns FindScenesFindScenesFindScenesResultTypeScenesScene.Date, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetDate() string { return v.Date }

// GetDetails returns FindScenesFindScenesFindScenesResultTypeScenesScene.Details, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetDetails() string { return v.Details }

// GetRating100 returns FindScenesFindScenesFindScenesResultTypeScenesScene.Rating100, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetRating100() int { return v.Rating100 }

// GetOrganized returns FindScenesFindScenesFindScenesResultTypeScenesScene.Organized, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetOrganized() bool { return v.Organized }

// GetCreated_at returns FindScenesFindScenesFindScenesResultTypeScenesScene.Created_at, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetCreated_at() time.Time {
	return v.Created_at
}

// GetUpdated_at returns FindScenesFindScenesFindScenesResultTypeScenesScene.Updated_at, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetUpdated_at() time.Time {
	return v.Updated_at
}

// GetFiles returns FindScenesFindScenesFindScenesResultTypeScenesScene.Files, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetFiles() []FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile {
	return v.Files
}

// GetStudio returns FindScenesFindScenesFindScenesResultTypeScenesScene.Studio, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetStudio() FindScenesFindScenesFindScenesResultTypeScenesSceneStudio {
	return v.Studio
}

// GetTags returns FindScenesFindScenesFindScenesResultTypeScenesScene.Tags, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetTags() []FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag {
	return v.Tags
}

// GetPerformers returns FindScenesFindScenesFindScenesResultTypeScenesScene.Performers, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetPerformers() []FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer {
	return v.Performers
}

// FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile includes the requested fields of the GraphQL type VideoFile.
type FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile struct {
	Path string `json:"path"`
}

// GetPath returns FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile.Path, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile) GetPath() string {
	return v.Path
}

// FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer includes the requested fields of the GraphQL type Performer.
type FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer struct {
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	Birthdate string     `json:"birthdate"`
	Gender    GenderEnum `json:"gender"`
}

// GetId returns FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer.Id, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer) GetId() string {
	return v.Id
}

// GetName returns FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer.Name, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer) GetName() string {
	return v.Name
}

// GetBirthdate returns FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer.Birthdate, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer) GetBirthdate() string {
	return v.Birthdate
}

// GetGender returns FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer.Gender, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScenePerformersPerformer) GetGender() GenderEnum {
	return v.Gender
}

// FindScenesFindScenesFindScenesResultTypeScenesSceneStudio includes the requested fields of the GraphQL type Studio.
type FindScenesFindScenesFindScenesResultTypeScenesSceneStudio struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns FindScenesFindScenesFindScenesResultTypeScenesSceneStudio.Id, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesSceneStudio) GetId() string { return v.Id }

// GetName returns FindScenesFindScenesFindScenesResultTypeScenesSceneStudio.Name, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesSceneStudio) GetName() string { return v.Name }

// FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag includes the requested fields of the GraphQL type Tag.
type FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// GetId returns FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag.Id, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag) GetId() string { return v.Id }

// GetName returns FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag.Name, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesSceneTagsTag) GetName() string { return v.Name }

// FindScenesResponse is returned by FindScenes on success.
type FindScenesResponse struct {
	// A function which queries Scene objects
	FindScenes FindScenesFindScenesFindScenesResultType `json:"findScenes"`
}

// GetFindScenes returns FindScenesResponse.FindScenes, and is useful for accessing the field via an interface.
func (v *FindScenesResponse) GetFindScenes() FindScenesFindScenesFindScenesResultType {
	return v.FindScenes
}

type GenderEnum string

const (
	GenderEnumMale              GenderEnum = "MALE"
	GenderEnumFemale            GenderEnum = "FEMALE"
	GenderEnumTransgenderMale   GenderEnum = "TRANSGENDER_MALE"
	GenderEnumTransgenderFemale GenderEnum = "TRANSGENDER_FEMALE"
	GenderEnumIntersex          GenderEnum = "INTERSEX"
	GenderEnumNonBinary         GenderEnum = "NON_BINARY"
)

// __FindGalleriesInput is used internally by genqlient
type __FindGalleriesInput struct {
	Filter FindFilter `json:"filter"`
}

// GetFilter returns __FindGalleriesInput.Filter, and is useful for accessing the field via an interface.
func (v *__FindGalleriesInput) GetFilter() FindFilter { return v.Filter }

// __FindScenesInput is used internally by genqlient
type __FindScenesInput struct {
	Filter FindFilter `json:"filter"`
}

// GetFilter returns __FindScenesInput.Filter, and is useful for accessing the field via an interface.
func (v *__FindScenesInput) GetFilter() FindFilter { return v.Filter }

// The query or mutation executed by FindGalleries.
const FindGalleries_Operation = `
query FindGalleries ($filter: FindFilterType) {
	findGalleries(filter: $filter) {
		count
		galleries {
			id
			title
			date
			details
			rating100
			organized
			created_at
			updated_at
			image_count
			folder {
				path
			}
			files {
				path
			}
			studio {
				id
				name
			}
			tags {
				id
				name
			}
			performers {
				id
				name
				birthdate
				gender
			}
		}
	}
}
`

func FindGalleries(
	ctx context.Context,
	client graphql.Client,
	filter FindFilter,
) (*FindGalleriesResponse, error) {
	req := &graphql.Request{
		OpName: "FindGalleries",
		Query:  FindGalleries_Operation,
		Variables: &__FindGalleriesInput{
			Filter: filter,
		},
	}
	var err error

	var data FindGalleriesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by FindScenes.
const FindScenes_Operation = `
query FindScenes ($filter: FindFilterType) {
	findScenes(filter: $filter) {
		count
		scenes {
			id
			title
			date
			details
			rating100
			organized
			created_at
			updated_at
			files {
				path
			}
			studio {
				id
				name
			}
			tags {
				id
				name
			}
			performers {
				id
				name
				birthdate
				gender
			}
		}
	}
}
`

func FindScenes(
	ctx context.Context,
	client graphql.Client,
	filter FindFilter,
) (*FindScenesResponse, error) {
	req := &graphql.Request{
		OpName: "FindScenes",
		Query:  FindScenes_Operation,
		Variables: &__FindScenesInput{
			Filter: filter,
		},
	}
	var err error

	var data FindScenesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
