// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package stash

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// FindGalleriesFindGalleriesFindGalleriesResultType includes the requested fields of the GraphQL type FindGalleriesResultType.
type FindGalleriesFindGalleriesFindGalleriesResultType struct {
	Count     int                                                                 `json:"count"`
	Galleries []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery `json:"galleries"`
}

// GetCount returns FindGalleriesFindGalleriesFindGalleriesResultType.Count, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultType) GetCount() int { return v.Count }

// GetGalleries returns FindGalleriesFindGalleriesFindGalleriesResultType.Galleries, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultType) GetGalleries() []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery {
	return v.Galleries
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery includes the requested fields of the GraphQL type Gallery.
// The GraphQL type's documentation follows.
//
// Gallery type
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery struct {
	Id     string                                                                              `json:"id"`
	Title  string                                                                              `json:"title"`
	Folder FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder             `json:"folder"`
	Files  []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile `json:"files"`
}

// GetId returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Id, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetId() string {
	return v.Id
}

// GetTitle returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Title, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetTitle() string {
	return v.Title
}

// GetFolder returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Folder, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetFolder() FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder {
	return v.Folder
}

// GetFiles returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery.Files, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGallery) GetFiles() []FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile {
	return v.Files
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile includes the requested fields of the GraphQL type GalleryFile.
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile struct {
	Path string `json:"path"`
}

// GetPath returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile.Path, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFilesGalleryFile) GetPath() string {
	return v.Path
}

// FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder includes the requested fields of the GraphQL type Folder.
type FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder struct {
	Path string `json:"path"`
}

// GetPath returns FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder.Path, and is useful for accessing the field via an interface.
func (v *FindGalleriesFindGalleriesFindGalleriesResultTypeGalleriesGalleryFolder) GetPath() string {
	return v.Path
}

// FindGalleriesResponse is returned by FindGalleries on success.
type FindGalleriesResponse struct {
	FindGalleries FindGalleriesFindGalleriesFindGalleriesResultType `json:"findGalleries"`
}

// GetFindGalleries returns FindGalleriesResponse.FindGalleries, and is useful for accessing the field via an interface.
func (v *FindGalleriesResponse) GetFindGalleries() FindGalleriesFindGalleriesFindGalleriesResultType {
	return v.FindGalleries
}

// FindScenesFindScenesFindScenesResultType includes the requested fields of the GraphQL type FindScenesResultType.
type FindScenesFindScenesFindScenesResultType struct {
	Count  int                                                   `json:"count"`
	Scenes []FindScenesFindScenesFindScenesResultTypeScenesScene `json:"scenes"`
}

// GetCount returns FindScenesFindScenesFindScenesResultType.Count, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultType) GetCount() int { return v.Count }

// GetScenes returns FindScenesFindScenesFindScenesResultType.Scenes, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultType) GetScenes() []FindScenesFindScenesFindScenesResultTypeScenesScene {
	return v.Scenes
}

// FindScenesFindScenesFindScenesResultTypeScenesScene includes the requested fields of the GraphQL type Scene.
type FindScenesFindScenesFindScenesResultTypeScenesScene struct {
	Id    string                                                              `json:"id"`
	Title string                                                              `json:"title"`
	Files []FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile `json:"files"`
}

// GetId returns FindScenesFindScenesFindScenesResultTypeScenesScene.Id, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetId() string { return v.Id }

// GetTitle returns FindScenesFindScenesFindScenesResultTypeScenesScene.Title, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetTitle() string { return v.Title }

// GetFiles returns FindScenesFindScenesFindScenesResultTypeScenesScene.Files, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesScene) GetFiles() []FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile {
	return v.Files
}

// FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile includes the requested fields of the GraphQL type VideoFile.
type FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile struct {
	Path string `json:"path"`
}

// GetPath returns FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile.Path, and is useful for accessing the field via an interface.
func (v *FindScenesFindScenesFindScenesResultTypeScenesSceneFilesVideoFile) GetPath() string {
	return v.Path
}

// FindScenesResponse is returned by FindScenes on success.
type FindScenesResponse struct {
	// A function which queries Scene objects
	FindScenes FindScenesFindScenesFindScenesResultType `json:"findScenes"`
}

// GetFindScenes returns FindScenesResponse.FindScenes, and is useful for accessing the field via an interface.
func (v *FindScenesResponse) GetFindScenes() FindScenesFindScenesFindScenesResultType {
	return v.FindScenes
}

// GetStatsResponse is returned by GetStats on success.
type GetStatsResponse struct {
	// Get stats
	Stats GetStatsStatsStatsResultType `json:"stats"`
}

// GetStats returns GetStatsResponse.Stats, and is useful for accessing the field via an interface.
func (v *GetStatsResponse) GetStats() GetStatsStatsStatsResultType { return v.Stats }

// GetStatsStatsStatsResultType includes the requested fields of the GraphQL type StatsResultType.
type GetStatsStatsStatsResultType struct {
	Scene_count     int     `json:"scene_count"`
	Scenes_size     float64 `json:"scenes_size"`
	Gallery_count   int     `json:"gallery_count"`
	Performer_count int     `json:"performer_count"`
}

// GetScene_count returns GetStatsStatsStatsResultType.Scene_count, and is useful for accessing the field via an interface.
func (v *GetStatsStatsStatsResultType) GetScene_count() int { return v.Scene_count }

// GetScenes_size returns GetStatsStatsStatsResultType.Scenes_size, and is useful for accessing the field via an interface.
func (v *GetStatsStatsStatsResultType) GetScenes_size() float64 { return v.Scenes_size }

// GetGallery_count returns GetStatsStatsStatsResultType.Gallery_count, and is useful for accessing the field via an interface.
func (v *GetStatsStatsStatsResultType) GetGallery_count() int { return v.Gallery_count }

// GetPerformer_count returns GetStatsStatsStatsResultType.Performer_count, and is useful for accessing the field via an interface.
func (v *GetStatsStatsStatsResultType) GetPerformer_count() int { return v.Performer_count }

// __FindGalleriesInput is used internally by genqlient
type __FindGalleriesInput struct {
	Filter FindFilter `json:"filter"`
}

// GetFilter returns __FindGalleriesInput.Filter, and is useful for accessing the field via an interface.
func (v *__FindGalleriesInput) GetFilter() FindFilter { return v.Filter }

// __FindScenesInput is used internally by genqlient
type __FindScenesInput struct {
	Filter FindFilter `json:"filter"`
}

// GetFilter returns __FindScenesInput.Filter, and is useful for accessing the field via an interface.
func (v *__FindScenesInput) GetFilter() FindFilter { return v.Filter }

// The query or mutation executed by FindGalleries.
const FindGalleries_Operation = `
query FindGalleries ($filter: FindFilterType) {
	findGalleries(filter: $filter) {
		count
		galleries {
			id
			title
			folder {
				path
			}
			files {
				path
			}
		}
	}
}
`

func FindGalleries(
	ctx context.Context,
	client graphql.Client,
	filter FindFilter,
) (*FindGalleriesResponse, error) {
	req := &graphql.Request{
		OpName: "FindGalleries",
		Query:  FindGalleries_Operation,
		Variables: &__FindGalleriesInput{
			Filter: filter,
		},
	}
	var err error

	var data FindGalleriesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by FindScenes.
const FindScenes_Operation = `
query FindScenes ($filter: FindFilterType) {
	findScenes(filter: $filter) {
		count
		scenes {
			id
			title
			files {
				path
			}
		}
	}
}
`

func FindScenes(
	ctx context.Context,
	client graphql.Client,
	filter FindFilter,
) (*FindScenesResponse, error) {
	req := &graphql.Request{
		OpName: "FindScenes",
		Query:  FindScenes_Operation,
		Variables: &__FindScenesInput{
			Filter: filter,
		},
	}
	var err error

	var data FindScenesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetStats.
const GetStats_Operation = `
query GetStats {
	stats {
		scene_count
		scenes_size
		gallery_count
		performer_count
	}
}
`

func GetStats(
	ctx context.Context,
	client graphql.Client,
) (*GetStatsResponse, error) {
	req := &graphql.Request{
		OpName: "GetStats",
		Query:  GetStats_Operation,
	}
	var err error

	var data GetStatsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
